-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 00:10:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hms_new
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hms_new
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hms_new` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hms_new` ;

-- -----------------------------------------------------
-- Table `hms_new`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hms_new`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `contactNumber` BIGINT NULL,
  `address` TEXT NULL,
  `registrationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isAdmin` TINYINT(1) NULL DEFAULT 0,
  `isStaff` TINYINT(1) NULL DEFAULT 0,
  `isActive` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hms_new`.`specializations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hms_new`.`specializations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `creationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hms_new`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hms_new`.`doctors` (
  `id` INT NOT NULL,
  `specilizationId` INT NULL DEFAULT NULL,
  `fees` VARCHAR(255) NULL DEFAULT NULL,
  `contactNumber` BIGINT NULL DEFAULT NULL,
  `creationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_doctors_users_idx` (`id` ASC) VISIBLE,
  INDEX `fk_doctors_doctorspecilization1_idx` (`specilizationId` ASC) VISIBLE,
  CONSTRAINT `fk_doctors_users`
    FOREIGN KEY (`id`)
    REFERENCES `hms_new`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctors_doctorspecilization1`
    FOREIGN KEY (`specilizationId`)
    REFERENCES `hms_new`.`specializations` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hms_new`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hms_new`.`appointments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doctorId` INT NOT NULL,
  `patientId` INT NOT NULL,
  `consultancyFees` INT NULL DEFAULT NULL,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `time` VARCHAR(255) NULL DEFAULT NULL,
  `postingDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `patientStatus` INT NULL DEFAULT NULL,
  `doctorStatus` INT NULL DEFAULT NULL,
  `updationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_appointment_doctors1_idx` (`doctorId` ASC) VISIBLE,
  INDEX `fk_appointments_users1_idx` (`patientId` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_doctors1`
    FOREIGN KEY (`doctorId`)
    REFERENCES `hms_new`.`doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_users1`
    FOREIGN KEY (`patientId`)
    REFERENCES `hms_new`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hms_new`.`contact_us`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hms_new`.`contact_us` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `contactNumber` BIGINT NULL DEFAULT NULL,
  `message` MEDIUMTEXT NULL DEFAULT NULL,
  `postingDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `adminRemark` MEDIUMTEXT NULL DEFAULT NULL,
  `updationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isRead` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hms_new`.`medical_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hms_new`.`medical_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patientId` INT NOT NULL,
  `bloodPressure` VARCHAR(200) NULL DEFAULT NULL,
  `bloodSugar` VARCHAR(200) NOT NULL,
  `weight` VARCHAR(100) NULL DEFAULT NULL,
  `temperature` VARCHAR(200) NULL DEFAULT NULL,
  `medicalPrescription` MEDIUMTEXT NULL DEFAULT NULL,
  `creationDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_medical_history_users1_idx` (`patientId` ASC) VISIBLE,
  CONSTRAINT `fk_medical_history_users1`
    FOREIGN KEY (`patientId`)
    REFERENCES `hms_new`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hms_new`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hms_new`.`pages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM("about", "contact") NULL DEFAULT NULL,
  `title` VARCHAR(200) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  `contactNumber` BIGINT NULL DEFAULT NULL,
  `updationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `openingTime` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hms_new`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hms_new`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `isDoctor` TINYINT(1) NULL DEFAULT 0,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `ip` BINARY(16) NULL DEFAULT NULL,
  `loginTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `logout` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_logs_users1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_logs_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `hms_new`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
